### ISSUE TITLE
Something with pinetry got merged in git-secret. Investigate if this can solve problem with public key cashing

### ISSUE THREAD

**Issue by doozMen** [dooZdev/Highway#40]
https://github.com/sobolevn/git-secret/pull/490

**Comment by joshrabinowitz** [comment]
@doozMen did this previously work, and then stop working? From my reading of the code we haven't really changed how `gpg --pinentry=loopback` is used.

If it did previously work and then stopped working, can you help us to narrow down which change caused the issue - IE what version (or git-sha) of git-secret did this work with? Can you find a commit or PR or version change that is related to this breaking?

Thanks very much.

**Comment by joshrabinowitz** [comment]
@doozMen we have merged sobolevn/git-secret#490 which should allow `--pinentry` to be set as needed.

**Comment by joshrabinowitz** [comment]
@doozMen if you still have issues with specifying --pinentry settings, please let us know. For now, closing this issue as 'fixed'.

**Comment by doozMen** [comment]
@joshrabinowitz I had to stop the work on this part of the project. Will pick it up later. It is not clear that it is fixed for me but I can also blame it to my lack of knowledge so not sure I can say this is fixed.

**Comment by joshrabinowitz** [comment]
@doozMen what error do you get with git-secret that caused you to file this issue?
